Make srcenv undo succeed when SRCENV_UNDO is not set

diff --git a/srcenv b/srcenv
--- a/srcenv
+++ b/srcenv
@@ -158,18 +158,17 @@ err() {
         '')       echo   >&2 '' ;;
         $escape*) printf >&2 '%s\n' "$1" ;;
 
-        $jq:\ *null*parsed*)  echo >&2 "${BOLD}${RED}error:${NORMAL} ${YELLOW}SRCENV_UNDO${NORMAL} environment variable is not set" ;;
-        $jq:\ *JSON*parsing*) if [ -n "$SRCENV_UNDO" ]; then
-                                  echo >&2 "${BOLD}${RED}error:${NORMAL} ${YELLOW}SRCENV_UNDO${NORMAL} environment variable contains invalid JSON: ${RED}$SRCENV_UNDO${NORMAL}"
-                              else
-                                  echo >&2 "${BOLD}${RED}error:${NORMAL} ${YELLOW}SRCENV_UNDO${NORMAL} environment variable is empty"
-                              fi ;;
+        $jq:\ *\<unknown\>*parsing*)
+                 error=${1#"$jq": }
+                 error=${error#error*: }
+                 echo >&2 "${BOLD}${RED}error:${NORMAL} ${YELLOW}SRCENV_UNDO${NORMAL} environment variable contains ${RED}invalid JSON${NORMAL}: $error" ;;
+
         $jq:\ *) LF='
 '
                  error=${1#"$jq": }
                  error=${error#error: }
                  error=${error%%, line 1:"${LF}"*}
-                 echo   >&2 "${BOLD}${RED}error:${NORMAL} ${BOLD}Invalid format:${NORMAL} $error" ;;
+                 echo >&2 "${BOLD}${RED}error:${NORMAL} ${BOLD}Invalid format:${NORMAL} $error" ;;
 
         *) printf '%s\n' "$1" | while IFS= read -r line; do
                line=${line#"$0": }
@@ -225,7 +224,7 @@ init() {
 $cmd() {
     case \$1 in
         ''|-\?|-h|--help|-v|--version) $0 \"\$@\" ;;
-        *) eval \"\$($0 $shell --backup \${SRCENV_UNDO:+--undo} \"\$@\")\" ;;
+        *) eval \"\$($0 $shell --backup --undo \"\$@\")\" ;;
     esac
 }" ;;
         csh|tcsh|\
@@ -271,8 +270,8 @@ setformat() {
                              '\($k)=' ;;
         json)            format=. ;;
         bat|cmd)         fmt 'set \"\($k)=\(.[$k] | gsub("\n"; "%LF%") | gsub("\""; "^\""))\"' \
-                             'set \($k)=';
-                         prefix='"set LFM=^\n\n\nset LF=^^^%LFM%%LFM%^%LFM%%LFM%\n" + ([';
+                             'set \($k)='
+                         prefix='"set LFM=^\n\n\nset LF=^^^%LFM%%LFM%^%LFM%%LFM%\n" + (['
                          suffix='] | join("\n")) + "\nset LFM=\nset LF="' ;;
         launchctl)       fmt 'launchctl setenv \($k) \(.[$k]|@sh)' \
                              'launchctl unsetenv \($k)' ;;
@@ -311,10 +310,10 @@ run() {
             -f=*|--format=*) value=$(parse "${1%%=*}" "${1#*=}") || exit $?
                              fmt "${value%\?\?*}" "${value#*\?\?}"; shift ;;
 
-            -b|--backup)   backup=1;                                  shift ;;
-            -u|--undo)     undo='env.SRCENV_UNDO | fromjson | . += '; shift ;;
-            -e|--export)   export=--export;                           shift ;;
-            -l|--local)    export=0;                                  shift ;;
+            -b|--backup)   backup=1;                                          shift ;;
+            -u|--undo)     undo='env.SRCENV_UNDO // "{}" | fromjson | . += '; shift ;;
+            -e|--export)   export=--export;                                   shift ;;
+            -l|--local)    export=0;                                          shift ;;
             -s|--sort)     keys='keys[] as $k';
                            sort='to_entries | sort_by(.key) | from_entries'; shift ;;
             -U|--unsorted) keys='keys_unsorted[] as $k'; sort=.;             shift ;;
